# Generated by Django 3.0.6 on 2020-05-07 13:55

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('other_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=12, unique=True, validators=[contacts.models.validate_phone])),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'unique_together': {('first_name', 'last_name', 'phone_number')},
            },
        ),
    ]
