# Generated by Django 3.0.6 on 2020-05-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200510_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='other_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
