# Generated by Django 3.0.6 on 2020-05-16 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20200516_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttag',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacttags', to='contacts.Contact'),
        ),
        migrations.AlterUniqueTogether(
            name='contacttag',
            unique_together={('contact', 'tag')},
        ),
    ]
