# Generated by Django 3.0.6 on 2020-05-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageInfo',
            new_name='SmsInfo',
        ),
    ]
