# Generated by Django 3.0.6 on 2020-05-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20200504_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsinfo',
            name='africastalking_response',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smsinfo',
            name='message_text',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smsinfo',
            name='success',
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='smsinfo',
            name='time_sent',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterOrderWithRespectTo(
            name='message',
            order_with_respect_to=None,
        ),
    ]
