# Generated by Django 3.0.6 on 2020-05-04 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20200504_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
    ]
