# Generated by Django 3.0.6 on 2020-05-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_auto_20200526_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsinfo',
            name='message_text',
            field=models.CharField(editable=False, max_length=160, null=True),
        ),
    ]
