# Generated by Django 3.0.6 on 2020-05-26 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20200526_1004'),
        ('accounts', '0005_auto_20200520_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.Contact'),
        ),
    ]
